### ISSUE TITLE
Contacting support page is not found

### ISSUE THREAD

**Issue by gugucode** [ibm-cloud-docs/fortigate-10g#21]
when I look at this page:
https://cloud.ibm.com/docs/infrastructure/fortigate-10g?topic=fortigate-10g-getting-help-and-support-for-fortigate-security-appliance-10gbps

then, click on the "Contacting support" button, it opens a new page (https://cloud.ibm.com/docs/get-support?topic=get-support-contacting-bluemix-support-dedicated-local), but this page is not found.

After I checked the "Getting Help and Support page" of firewall 1G, hardware firewall (shared) and hardware firewall (dedicated), the "Contacting support" page is not found too from those pages.

**Comment by jbmitch** [comment]
Link works, maybe was an issue at the time of the filing
