### ISSUE TITLE
Getting "Page Not Found" by clicking "Virtual Router Appliance" 

### ISSUE THREAD

**Issue by takeyan** [ibm-cloud-docs/fortigate-10g#23]
On an online document page (the URL is https://cloud.ibm.com/docs/infrastructure/virtual-router-appliance?topic=fortigate-10g-exploring-firewalls&locale=en), you will get "Page Not Found" when you click "Virtual Router Appliance" in the header of the table. 
[20190514_PageNotFoud.pptx](https://github.com/IBM-Bluemix-Docs/fortigate-10g/files/3175337/20190514_PageNotFoud.pptx)

**Comment by jbmitch** [comment]
Link works, maybe it was a server issue at the time of filing
