### ISSUE TITLE
Need description of the default DNS servers for FortiGate in FAQ

### ISSUE THREAD

**Issue by tetsuonatom** [ibm-cloud-docs/fortigate-10g#24]
### What is the default DNS servers of FortiGate?

By default, FortiGate uses FortiGuard's DNS servers:
- Primary: 208.91.112.53
- Secondary: 208.91.112.52

**Comment by austinmama** [comment]
@jbmitch  Addition to FAQ

**Comment by jbmitch** [comment]
Added to FAQs
