### ISSUE TITLE
Scrolling the Firewall Table

### ISSUE THREAD

**Issue by kintulpatadia** [ibm-cloud-docs/fortigate-10g#3]
Can we make sure that the column where all the features of firewall stays static, while you are scrolling to the right? Sometimes the customer wants to look at multiple features within the column and has to scroll left and right to make sure that is the right feature.

This would be something similiar to Excel feature of "Freezing Horizontal and Vertical Panes"

**Comment by jbmitch** [comment]
Sadly no, we have no control over table formatting, as that is dependent on the IBM Cloud Docs infrastructure. You can raise the issue with the IBM Cloud Docs platform development team if you would like. Contact Sebastian Fuhrer or Neal Tempe to find out how to open an issue.
